site_name: RaceAssist-docs
theme:
  name: material
  language: ja
  logo: null
  favicon: https://github.com/RaceAssist/RaceAssist-web/blob/main/public/favicon.png?raw=true
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.tabs
    - content.code.copy
  palette: 
    - scheme: default
      primary : blue
      accent: light blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary : blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search:
      lang: ja
repo_url: https://github.com/RaceAssist/RaceAssist-core
repo_name: RaceAssist-core
copyright: Copyright &copy; 2023 Nikomaru
